version: "3.8"

volumes:
  grafana-data:
  loki-data:

networks:
  gatornet:
    external: true

services:

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./config/observability/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    networks:
      - gatornet

  promtail:
    image: grafana/promtail:2.9.1
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./config/observability/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/log:/var/log:ro
      - /run/log/journal:/run/log/journal:ro
    depends_on:
      - loki
    networks:
      - gatornet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/observability/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - gatornet
